// src/pages/editor/EditorLoginPage.svelte
<script lang="ts">
  import { push } from "svelte-spa-router";
  import { authStore } from "../../stores/authStore";
  import { titleBarStore } from "../../stores/titleBarStore";
  import "./EditorLoginPage.css";

  let project = $state("democrats_abroad");
  let password = $state("");
  let error = $state<string | null>(null);
  let submitting = $state(false);

  titleBarStore.set({ title: "Sign in", progress: null, backPath: null });

  async function handleSubmit(e: Event) {
    e.preventDefault();
    error = null;
    submitting = true;
    try {
      const res = await fetch("/auth/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ project, teamName: "", contact: "", password }),
      });
      const data = (await res.json()) as {
        ok: boolean;
        isAdmin?: boolean;
        error?: string;
      };
      if (data.ok && data.isAdmin) {
        authStore.login(project, "", "", true);
        push("/editor");
      } else if (data.ok && !data.isAdmin) {
        error = "These credentials do not have organiser access.";
      } else {
        error = data.error ?? "Incorrect password.";
      }
    } catch {
      error = "Connection error. Please try again.";
    } finally {
      submitting = false;
    }
  }
</script>

<div class="editor-login">
  <div class="editor-login__header">
    <div class="editor-login__eyebrow">Organiser tools</div>
    <div class="editor-login__headline">Sign in</div>
  </div>
  <form onsubmit={handleSubmit} class="editor-login__form">
    <div class="editor-login__field">
      <label class="editor-login__label" for="project">Project</label>
      <input
        id="project"
        type="text"
        bind:value={project}
        required
        class="editor-login__input"
      />
    </div>
    <div
      class={error
        ? "editor-login__field--last-error"
        : "editor-login__field--last"}
    >
      <label class="editor-login__label" for="password">Admin password</label>
      <input
        id="password"
        type="password"
        bind:value={password}
        required
        class={`editor-login__input${error ? " editor-login__input--error" : ""}`}
      />
    </div>
    {#if error}
      <div class="editor-login__error">✕ {error}</div>
    {/if}
    <button
      type="submit"
      disabled={submitting}
      class={`editor-login__submit${submitting ? " editor-login__submit--loading" : ""}`}
    >
      {submitting ? "Signing in…" : "Sign in"}
    </button>
  </form>
</div>

// src/pages/editor/EditorLoginPage.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../../auth/AuthContext";
import "./EditorLoginPage.css";

export default function EditorLoginPage() {
  const navigate = useNavigate();
  const { login } = useAuth();
  const [project, setProject] = useState("democrats_abroad");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    setLoading(true);
    try {
      const res = await fetch("/auth/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ project, teamName: "", contact: "", password }),
      });
      const data = await res.json() as { ok: boolean; isAdmin?: boolean; error?: string };
      if (data.ok && data.isAdmin) {
        login(project, "", "", true);
        navigate("/editor");
      } else if (data.ok && !data.isAdmin) {
        setError("These credentials do not have organiser access.");
      } else {
        setError(data.error || "Incorrect password.");
      }
    } catch {
      setError("Connection error. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="editor-login">
      <div className="editor-login__header">
        <div className="editor-login__eyebrow">Organiser tools</div>
        <div className="editor-login__headline">Sign in</div>
      </div>
      <form onSubmit={handleSubmit} className="editor-login__form">
        <div className="editor-login__field">
          <label className="editor-login__label">Project</label>
          <input
            value={project}
            onChange={(e) => setProject(e.target.value)}
            required
            className="editor-login__input"
          />
        </div>
        <div
          className={
            error
              ? "editor-login__field--last-error"
              : "editor-login__field--last"
          }
        >
          <label className="editor-login__label">Admin password</label>
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            className={`editor-login__input${error ? " editor-login__input--error" : ""}`}
          />
        </div>
        {error ? <div className="editor-login__error">✕ {error}</div> : null}
        <button
          type="submit"
          disabled={loading}
          className={`editor-login__submit${loading ? " editor-login__submit--loading" : ""}`}
        >
          {loading ? "Signing in…" : "Sign in"}
        </button>
      </form>
    </div>
  );
}
