// src/pages/RoutePage.svelte
<script lang="ts" module>
  export { clampedNext, clampedPrev } from "../utils/routeNav";
</script>

<script lang="ts">
  import { push } from "svelte-spa-router";
  import { titleBarStore } from "../stores/titleBarStore";
  import { languageStore } from "../stores/languageStore";
  import { loadText } from "../utils/loadText";
  import { loadLocations } from "../utils/loadLocations";
  import { clampedNext, clampedPrev } from "../utils/routeNav";
  import ChallengeCard from "../components/ChallengeCard.svelte";
  import type { RoutesData, Location } from "../types/data";
  import "./RoutePage.css";

  let { params }: { params: { project: string; city: string; route: string } } = $props();

  let storageKey = $derived(`${params.project}/${params.city}/${params.route}`);
  let routesText = $state<RoutesData | null>(null);
  let routeData = $derived(routesText?.[params.route] ?? null);
  let locationPaths = $derived(
    routeData ? routeData.locations.map((id: string) => `projects/${params.project}/${params.city}/${id}`) : []
  );
  let locations = $state<Location[]>([]);

  const _savedIndex = localStorage.getItem(storageKey);
  const _parsedIndex = _savedIndex ? parseInt(_savedIndex, 10) : 0;
  let currentIndex = $state<number>(isNaN(_parsedIndex) ? 0 : _parsedIndex);
  let direction = $state<"next" | "prev">("next");
  let touchStartX = $state<number | null>(null);

  $effect(() => {
    const lang = $languageStore.currentLang;
    loadText<RoutesData>(lang, `projects/${params.project}/${params.city}/routes`).then((data) => {
      routesText = data;
    });
  });

  $effect(() => {
    const lang = $languageStore.currentLang;
    if (locationPaths.length > 0) {
      loadLocations(lang, locationPaths).then((locs) => {
        locations = locs;
      });
    }
  });

  $effect(() => {
    titleBarStore.set({
      title: params.route.replace(/_/g, " "),
      progress: locations.length > 0 ? { current: currentIndex + 1, total: locations.length } : null,
      backPath: `/${params.project}/${params.city}`,
    });
  });

  $effect(() => {
    localStorage.setItem(storageKey, String(currentIndex));
  });

  function handleTouchStart(e: TouchEvent) {
    touchStartX = e.touches[0].clientX;
  }

  function handleTouchEnd(e: TouchEvent) {
    if (touchStartX !== null) {
      const delta = e.changedTouches[0].clientX - touchStartX;
      touchStartX = null;
      if (delta < -60) {
        direction = "next";
        currentIndex = clampedNext(currentIndex, locations.length);
      } else if (delta > 60) {
        direction = "prev";
        currentIndex = clampedPrev(currentIndex);
      }
    }
  }

  let currentLocation = $derived(locations[currentIndex]);
</script>

<div
  class="route-page"
  role="region"
  aria-label="Hunt route"
  ontouchstart={handleTouchStart}
  ontouchend={handleTouchEnd}
>
  {#if locations.length > 0 && currentLocation}
    <div class="route-page__cards" style={`animation: ${direction === "next" ? "slideInFromRight" : "slideInFromLeft"} 250ms ease-out`}>
      <ChallengeCard
        location={currentLocation}
        isLast={currentIndex === locations.length - 1}
        index={currentIndex + 1}
        routeId={params.route}
      />
    </div>
  {:else}
    <p class="route-page__loading">Loading…</p>
  {/if}

  <div class="route-page__nav">
    <div class="route-page__nav-slot">
      {#if currentIndex > 0}
        <button
          aria-label="Previous stop"
          onclick={() => { direction = "prev"; currentIndex = clampedPrev(currentIndex); }}
          class="route-page__prev-btn"
        >
          <!-- ChevronLeft -->
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 18 9 12 15 6"/></svg>
          Prev
        </button>
      {/if}
    </div>

    <button onclick={() => push(`/${params.project}/${params.city}`)} class="route-page__exit-btn">
      Exit
    </button>

    <div class="route-page__nav-slot--right">
      {#if currentIndex < locations.length - 1}
        <button
          aria-label="Next stop"
          onclick={() => { direction = "next"; currentIndex = clampedNext(currentIndex, locations.length); }}
          class="route-page__next-btn"
        >
          Next
          <!-- ChevronRight -->
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"/></svg>
        </button>
      {/if}
    </div>
  </div>
</div>

// src/pages/RoutePage.jsx
import { useState, useEffect, useRef } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useText } from "../hooks/useText";
import { useLocations } from "../hooks/useLocations";
import { useTheme } from "../theme/ThemeContext";
import { useTitleBar } from "../theme/TitleBarContext";
import ChallengeCard from "../components/ChallengeCard";
import { ChevronLeft, ChevronRight } from "lucide-react";
import "./RoutePage.css";

export function clampedNext(current, total) {
  if (total <= 0) return 0;
  return Math.min(current + 1, total - 1);
}

export function clampedPrev(current) {
  return Math.max(current - 1, 0);
}

export default function RoutePage() {
  const { project, city, route } = useParams();
  const navigate = useNavigate();
  const storageKey = `${project}/${city}/${route}`;
  const { theme } = useTheme();

  const { text: routesText, loading: routesLoading } = useText(
    `projects/${project}/${city}/routes`,
  );

  const routeData = !routesLoading && routesText ? routesText[route] : null;
  const locationPaths = routeData
    ? routeData.locations.map((id) => `projects/${project}/${city}/${id}`)
    : [];

  const { locations, loading: locationsLoading } = useLocations(locationPaths);

  const [currentIndex, setCurrentIndex] = useState(() => {
    const saved = localStorage.getItem(storageKey);
    const parsed = saved ? parseInt(saved, 10) : 0;
    return isNaN(parsed) ? 0 : parsed;
  });
  const [direction, setDirection] = useState("next");

  const touchStartX = useRef(null);

  useEffect(() => {
    localStorage.setItem(storageKey, currentIndex);
  }, [storageKey, currentIndex]);

  useTitleBar({
    title: route.replace(/_/g, " "),
    progress:
      locations.length > 0
        ? { current: currentIndex + 1, total: locations.length }
        : null,
    backPath: `/${project}/${city}`,
  });

  const handleTouchStart = (e) => {
    touchStartX.current = e.touches[0].clientX;
  };

  const handleTouchEnd = (e) => {
    if (touchStartX.current === null) return;
    const delta = e.changedTouches[0].clientX - touchStartX.current;
    touchStartX.current = null;
    if (delta < -60) {
      setDirection("next");
      setCurrentIndex((i) => clampedNext(i, locations.length));
    } else if (delta > 60) {
      setDirection("prev");
      setCurrentIndex((i) => clampedPrev(i));
    }
  };

  if (routesLoading || locationsLoading) {
    return (
      <div
        style={{ padding: 24, background: theme.background, color: theme.text }}
      >
        Loading…
      </div>
    );
  }

  if (!routeData) {
    return (
      <div
        style={{ padding: 24, background: theme.background, color: theme.text }}
      >
        Route not found.
      </div>
    );
  }

  const location = locations[currentIndex];
  if (!location) {
    return (
      <div
        style={{ padding: 24, background: theme.background, color: theme.text }}
      >
        No locations found for this route.
      </div>
    );
  }

  return (
    <div
      onTouchStart={handleTouchStart}
      onTouchEnd={handleTouchEnd}
      className="route-page"
    >
      <div className="route-page__cards">
        <div
          key={currentIndex}
          style={{
            animation: `${direction === "next" ? "slideInFromRight" : "slideInFromLeft"} 250ms ease-out`,
          }}
        >
          <ChallengeCard
            location={location}
            isLast={currentIndex === locations.length - 1}
            index={currentIndex + 1}
            routeId={route}
          />
        </div>
      </div>

      <div className="route-page__nav">
        <div className="route-page__nav-slot">
          {currentIndex > 0 && (
            <button
              aria-label="Previous stop"
              onClick={() => {
                setDirection("prev");
                setCurrentIndex((i) => clampedPrev(i));
              }}
              className="route-page__prev-btn"
            >
              <ChevronLeft size={16} aria-hidden /> Prev
            </button>
          )}
        </div>

        <button
          onClick={() => navigate(`/${project}/${city}`)}
          className="route-page__exit-btn"
        >
          Exit
        </button>

        <div className="route-page__nav-slot--right">
          {currentIndex < locations.length - 1 && (
            <button
              aria-label="Next stop"
              onClick={() => {
                setDirection("next");
                setCurrentIndex((i) => clampedNext(i, locations.length));
              }}
              className="route-page__next-btn"
            >
              Next <ChevronRight size={16} aria-hidden />
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
