// src/components/ChallengeForm.tsx
import { useState, useRef } from "react";
import { useAuth } from "../auth/AuthContext";
import { Camera, Flag } from "lucide-react";
import type { FormField, FormFieldType } from "../types/data";
import "./ChallengeForm.css";

const VALID_TYPES: FormFieldType[] = [
  "string",
  "number",
  "boolean",
  "radio",
  "multiple",
  "photo",
];

const FormDivider = () => (
  <div className="cf-divider" aria-hidden>
    <span className="cf-divider__line" />
    <Flag size={12} className="cf-divider__icon" />
    <span className="cf-divider__line" />
  </div>
);

function checkDefinition(field: FormField): string | null {
  if (!VALID_TYPES.includes(field.type)) return `unknown type "${field.type}"`;
  if (field.type === "radio" && (!field.options || field.options.length === 0))
    return "radio field missing options";
  if (
    field.type === "multiple" &&
    (!field.options || field.options.length === 0)
  )
    return "multiple field missing options";
  if (field.type === "multiple" && (field.min == null || field.max == null))
    return "multiple field missing min/max";
  if (
    field.type === "multiple" &&
    field.min !== undefined &&
    field.max !== undefined &&
    field.min > field.max
  )
    return "multiple field: min > max";
  return null;
}

type SubmitState = "idle" | "submitting" | "success" | "error";
type UploadState = "idle" | "uploading" | "success" | "error";
type FieldValues = Record<string, string | number | boolean | string[]>;

interface ChallengeFormProps {
  form: FormField[];
  locationId: number;
  routeId?: string;
}

export default function ChallengeForm({
  form,
  locationId,
  routeId,
}: ChallengeFormProps) {
  const { activeAuth } = useAuth();
  const [values, setValues] = useState<FieldValues>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitState, setSubmitState] = useState<SubmitState>("idle");
  const [maxWarning, setMaxWarning] = useState<string | null>(null);
  const maxWarningTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [uploadState, setUploadState] = useState<UploadState>("idle");
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [showConfirm, setShowConfirm] = useState(false);

  async function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    setUploadState("uploading");
    const body = new FormData();
    body.append("photo", file);
    body.append("locationId", String(locationId));
    try {
      const res = await fetch("/upload", { method: "POST", body });
      const data = (await res.json()) as { ok: boolean };
      setUploadState(data.ok ? "success" : "error");
    } catch {
      setUploadState("error");
    }
  }

  function setValue(id: string, value: FieldValues[string]) {
    setValues((prev) => ({ ...prev, [id]: value }));
    setErrors((prev) => {
      const next = { ...prev };
      delete next[id];
      return next;
    });
  }

  function toggleMultiple(id: string, opt: string, max: number | undefined) {
    setValues((prev) => {
      const current = (prev[id] as string[]) ?? [];
      if (!current.includes(opt) && max !== undefined && current.length >= max) {
        clearTimeout(maxWarningTimer.current ?? undefined);
        setMaxWarning(id);
        maxWarningTimer.current = setTimeout(() => setMaxWarning(null), 1500);
        return prev;
      }
      const next = current.includes(opt)
        ? current.filter((v) => v !== opt)
        : [...current, opt];
      return { ...prev, [id]: next };
    });
    setErrors((prev) => {
      const next = { ...prev };
      delete next[id];
      return next;
    });
  }

  function validate(): Record<string, string> {
    const newErrors: Record<string, string> = {};
    for (const field of form) {
      if (checkDefinition(field)) continue;
      if (field.type === "boolean") continue;
      if (field.type === "radio" && !values[field.id])
        newErrors[field.id] = "Please select an option";
      if (field.type === "multiple") {
        const selected = (values[field.id] as string[]) ?? [];
        if (selected.length < (field.min ?? 0))
          newErrors[field.id] =
            `Select at least ${field.min} option${(field.min ?? 0) > 1 ? "s" : ""}`;
        else if (field.max !== undefined && selected.length > field.max)
          newErrors[field.id] =
            `Select at most ${field.max} option${field.max > 1 ? "s" : ""}`;
      }
      if (field.type === "string" && !String(values[field.id] ?? "").trim())
        newErrors[field.id] = "This field is required";
      if (
        field.type === "number" &&
        (values[field.id] === "" || values[field.id] === undefined)
      )
        newErrors[field.id] = "This field is required";
    }
    return newErrors;
  }

  async function submitAnswers() {
    setSubmitState("submitting");
    try {
      const res = await fetch("/form-submit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          timestamp: new Date().toISOString(),
          routeId: String(routeId),
          locationId: String(locationId),
          teamName: activeAuth?.teamName ?? "",
          email: activeAuth?.contact ?? "",
          fields: values,
        }),
      });
      const data = (await res.json()) as { ok: boolean };
      setSubmitState(data.ok ? "success" : "error");
    } catch {
      setSubmitState("error");
    }
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    const newErrors = validate();
    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }
    setShowConfirm(true);
  }

  async function handleConfirm() {
    setShowConfirm(false);
    await submitAnswers();
  }

  function renderField(field: FormField) {
    const defError = checkDefinition(field);
    if (defError) {
      return (
        <div key={field.id} className="cf-invalid-field">
          {`⚠ Invalid field "${field.id}": ${defError}`}
        </div>
      );
    }

    if (field.type === "photo") {
      return (
        <div key={field.id} className="cf-photo-wrap">
          <input
            ref={fileInputRef}
            type="file"
            accept="image/*"
            capture="environment"
            onChange={handleFileChange}
            style={{ display: "none" }}
          />
          {uploadState === "success" ? (
            <div className="cf-photo-success">✓ Photo submitted</div>
          ) : (
            <button
              data-testid="submit-btn"
              type="button"
              onClick={() => fileInputRef.current?.click()}
              disabled={uploadState === "uploading"}
              className={`cf-photo-btn cf-photo-btn--${uploadState}`}
            >
              {uploadState === "uploading" ? (
                "Uploading…"
              ) : uploadState === "error" ? (
                <>
                  <Camera
                    size={14}
                    aria-hidden
                    style={{ verticalAlign: "middle", marginRight: 4 }}
                  />{" "}
                  Try again
                </>
              ) : (
                <>
                  <Camera
                    size={14}
                    aria-hidden
                    style={{ verticalAlign: "middle", marginRight: 4 }}
                  />{" "}
                  {field.label ?? "Submit photo proof"}
                </>
              )}
            </button>
          )}
        </div>
      );
    }

    return (
      <div key={field.id} className="cf-field">
        {field.type === "boolean" ? (
          <label htmlFor={field.id} className="cf-label--checkbox">
            <input
              id={field.id}
              type="checkbox"
              checked={!!values[field.id]}
              onChange={(e) => setValue(field.id, e.target.checked)}
              className="cf-checkbox"
            />
            {field.label}
          </label>
        ) : (
          <>
            <label htmlFor={field.id} className="cf-label">
              {field.label}
            </label>
            {field.type === "string" ? (
              <input
                id={field.id}
                type="text"
                value={(values[field.id] as string) ?? ""}
                onChange={(e) => setValue(field.id, e.target.value)}
                className={`cf-input${errors[field.id] ? " cf-input--error" : ""}`}
              />
            ) : null}
            {field.type === "number" ? (
              <input
                id={field.id}
                type="number"
                value={(values[field.id] as number) ?? ""}
                onChange={(e) =>
                  setValue(
                    field.id,
                    e.target.value === "" ? "" : Number(e.target.value),
                  )
                }
                className={`cf-input${errors[field.id] ? " cf-input--error" : ""}`}
              />
            ) : null}
            {field.type === "radio" && field.options ? (
              <div className="cf-radio-group">
                {field.options.map((opt) => (
                  <label
                    key={opt}
                    htmlFor={`${field.id}-${opt}`}
                    className="cf-label--radio"
                  >
                    <input
                      id={`${field.id}-${opt}`}
                      type="radio"
                      name={field.id}
                      value={opt}
                      checked={values[field.id] === opt}
                      onChange={() => setValue(field.id, opt)}
                    />
                    {opt}
                  </label>
                ))}
              </div>
            ) : null}
            {field.type === "multiple" && field.options ? (
              <>
                <span className="cf-multi-hint">
                  Select{" "}
                  {field.min === field.max
                    ? field.min
                    : `${field.min}–${field.max}`}
                </span>
                <div className="cf-radio-group">
                  {field.options.map((opt) => (
                    <label
                      key={opt}
                      htmlFor={`${field.id}-${opt}`}
                      className="cf-label--radio"
                    >
                      <input
                        id={`${field.id}-${opt}`}
                        type="checkbox"
                        value={opt}
                        checked={((values[field.id] as string[]) ?? []).includes(opt)}
                        onChange={() => toggleMultiple(field.id, opt, field.max)}
                      />
                      {opt}
                    </label>
                  ))}
                </div>
                {maxWarning === field.id ? (
                  <div className="cf-max-warning">
                    Maximum of {field.max} option{field.max !== undefined && field.max > 1 ? "s" : ""}{" "}
                    reached
                  </div>
                ) : null}
              </>
            ) : null}
          </>
        )}
        {errors[field.id] ? (
          <div className="cf-error-msg">{errors[field.id]}</div>
        ) : null}
      </div>
    );
  }

  if (submitState === "success") {
    return <div className="cf-success">✓ Answers submitted</div>;
  }

  return (
    <form onSubmit={handleSubmit} style={{ marginTop: 14 }}>
      <FormDivider />
      {form.map(renderField)}
      <FormDivider />

      {submitState === "error" ? (
        <div className="cf-error-banner">
          Submission failed. Please try again.
        </div>
      ) : null}

      <button
        type="submit"
        disabled={submitState === "submitting"}
        className="cf-submit-btn"
      >
        {submitState === "submitting"
          ? "Submitting…"
          : submitState === "error"
            ? "Try again"
            : "Submit"}
      </button>

      {showConfirm ? (
        <div className="cf-confirm-overlay">
          <div className="cf-confirm-dialog">
            <p className="cf-confirm-msg">Submit your answers?</p>
            <div className="cf-confirm-actions">
              <button
                type="button"
                className="cf-confirm-cancel"
                onClick={() => setShowConfirm(false)}
              >
                Cancel
              </button>
              <button
                type="button"
                className="cf-confirm-ok"
                onClick={handleConfirm}
              >
                Confirm
              </button>
            </div>
          </div>
        </div>
      ) : null}
    </form>
  );
}

// src/components/ChallengeForm.svelte
<script lang="ts">
  import { Camera, Flag } from "lucide-svelte";
  import { authStore } from "../stores/authStore";
  import type { FormField, FormFieldType } from "../types/data";
  import "./ChallengeForm.css";

  const VALID_TYPES: FormFieldType[] = [
    "string",
    "number",
    "boolean",
    "radio",
    "multiple",
    "photo",
  ];

  type SubmitState = "idle" | "submitting" | "success" | "error";
  type UploadState = "idle" | "uploading" | "success" | "error";
  type FieldValues = Record<string, string | number | boolean | string[]>;

  let {
    form,
    locationId,
    routeId = undefined,
  }: { form: FormField[]; locationId: number; routeId?: string } = $props();

  let values = $state<FieldValues>({});
  let errors = $state<Record<string, string>>({});
  let submitState = $state<SubmitState>("idle");
  let uploadState = $state<UploadState>("idle");
  let showConfirm = $state(false);
  let fileInput: HTMLInputElement | undefined = $state();
  let maxWarningKeys = $state<Record<string, number>>({});

  function checkDefinition(field: FormField): string | null {
    if (!VALID_TYPES.includes(field.type)) return `unknown type "${field.type}"`;
    if (field.type === "radio" && (!field.options || field.options.length === 0)) {
      return "radio field missing options";
    }
    if (field.type === "multiple" && (!field.options || field.options.length === 0)) {
      return "multiple field missing options";
    }
    if (field.type === "multiple" && (field.min == null || field.max == null)) {
      return "multiple field missing min/max";
    }
    if (
      field.type === "multiple" &&
      field.min !== undefined &&
      field.max !== undefined &&
      field.min > field.max
    ) {
      return "multiple field: min > max";
    }
    return null;
  }

  async function handleFileChange(evt: Event) {
    const file = (evt.target as HTMLInputElement).files?.[0];
    if (!file) {
      return undefined;
    }
    uploadState = "uploading";
    const body = new FormData();
    body.append("photo", file);
    body.append("locationId", String(locationId));
    try {
      const res = await fetch("/upload", { method: "POST", body });
      const data = (await res.json()) as { ok: boolean };
      uploadState = data.ok ? "success" : "error";
    } catch {
      uploadState = "error";
    }
  }

  function validateValues(): Record<string, string> {
    const errs: Record<string, string> = {};
    for (const field of form) {
      if (field.type === "boolean" || field.type === "photo") continue;
      if (field.type === "string") {
        const v = values[field.id] as string | undefined;
        if (!v || v.trim() === "") errs[field.id] = "Required";
      } else if (field.type === "number") {
        const v = values[field.id];
        if (v === undefined || v === null || (typeof v === "number" && isNaN(v))) {
          errs[field.id] = "Required";
        }
      } else if (field.type === "radio") {
        if (!values[field.id]) errs[field.id] = "Please select an option";
      } else if (field.type === "multiple") {
        const selected = (values[field.id] as string[]) ?? [];
        const min = field.min ?? 1;
        if (selected.length < min) {
          errs[field.id] = `Please select at least ${min} option${min > 1 ? "s" : ""}`;
        }
      }
    }
    return errs;
  }

  function handleSubmit() {
    const newErrors: Record<string, string> = {};
    for (const field of form) {
      const def = checkDefinition(field);
      if (def) newErrors[field.id] = def;
    }
    errors = { ...validateValues(), ...newErrors };
    if (Object.keys(errors).length === 0) showConfirm = true;
  }

  async function handleConfirm() {
    showConfirm = false;
    submitState = "submitting";
    try {
      const payload = {
        locationId,
        routeId,
        teamName: $authStore.activeAuth?.teamName ?? "",
        contact: $authStore.activeAuth?.contact ?? "",
        answers: values,
      };
      const res = await fetch("/form-submit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      const data = (await res.json()) as { ok: boolean };
      submitState = data.ok ? "success" : "error";
    } catch {
      submitState = "error";
    }
  }

</script>

<div class="challenge-form">
  {#if submitState === "success"}
    <p class="cf-success">Submitted! ✓</p>
  {:else}
    <div class="cf-divider" aria-hidden="true">
      <span class="cf-divider__line"></span>
      <Flag size={12} aria-hidden="true" />
      <span class="cf-divider__line"></span>
    </div>

    {#each form as field (field.id)}
      {@const err = errors[field.id]}
      <div class="cf-field">
        {#if field.type === "photo"}
          <div class="cf-photo-wrap">
            <button
              class="cf-photo-btn"
              onclick={() => fileInput?.click()}
              disabled={uploadState === "uploading"}
            >
              <Camera size={16} aria-hidden="true" />
              {uploadState === "success" ? "Photo uploaded ✓" : uploadState === "uploading" ? "Uploading…" : field.label}
            </button>
            <input
              id={field.id}
              type="file"
              accept="image/*"
              capture="environment"
              class="cf-photo-input"
              bind:this={fileInput}
              onchange={handleFileChange}
            />
            {#if uploadState === "error"}
              <p class="cf-photo-error">Upload failed. Try again.</p>
            {/if}
          </div>
        {:else if field.type === "boolean"}
          <label class="cf-label--checkbox">
            {field.label}
            <input
              id={field.id}
              type="checkbox"
              class="cf-checkbox"
              bind:checked={values[field.id] as boolean}
            />
          </label>
        {:else}
          <label class="cf-label" for={field.id}>{field.label}</label>
          {#if err}<p class="cf-error-msg">{err}</p>{/if}
          {#if field.type === "string"}
            <input
              id={field.id}
              type="text"
              class="cf-input"
              class:cf-input--error={err}
              bind:value={values[field.id] as string}
            />
          {:else if field.type === "number"}
            <input
              id={field.id}
              type="number"
              inputmode="numeric"
              min="0"
              step="1"
              class="cf-input"
              class:cf-input--error={err}
              bind:value={values[field.id] as number}
              oninput={(e) => {
                const t = e.target as HTMLInputElement;
                t.value = t.value.replace(/[^0-9]/g, "");
              }}
            />
          {:else if field.type === "radio"}
            <div class="cf-radio-group">
              {#each field.options ?? [] as opt (opt)}
                <label class="cf-label--radio">
                  <input
                    type="radio"
                    name={field.id}
                    value={opt}
                    bind:group={values[field.id] as string}
                  />
                  {opt}
                </label>
              {/each}
            </div>
          {:else if field.type === "multiple"}
            {#if maxWarningKeys[field.id]}
              {#key maxWarningKeys[field.id]}
                <p class="cf-max-warning">You can only select {field.max}</p>
              {/key}
            {/if}
            <div class="cf-radio-group">
              {#each field.options ?? [] as opt (opt)}
                <label class="cf-label--radio">
                  <input
                    type="checkbox"
                    value={opt}
                    checked={(values[field.id] as string[] ?? []).includes(opt)}
                    onchange={(evt) => {
                      const target = evt.target as HTMLInputElement;
                      const cur = (values[field.id] as string[]) ?? [];
                      if (target.checked && field.max !== undefined && cur.length >= field.max) {
                        target.checked = false;
                        maxWarningKeys = { ...maxWarningKeys, [field.id]: (maxWarningKeys[field.id] ?? 0) + 1 };
                      } else {
                        values[field.id] = target.checked
                          ? [...cur, opt]
                          : cur.filter((val) => val !== opt);
                      }
                    }}
                  />
                  {opt}
                </label>
              {/each}
            </div>
          {/if}
        {/if}
      </div>
    {/each}

    <div class="cf-divider" aria-hidden="true">
      <span class="cf-divider__line"></span>
      <Flag size={12} aria-hidden="true" />
      <span class="cf-divider__line"></span>
    </div>

    {#if showConfirm}
      <div class="cf-confirm-overlay">
        <div class="cf-confirm-dialog">
          <p class="cf-confirm-msg">Submit your answers?</p>
          <div class="cf-confirm-actions">
            <button class="cf-confirm-cancel" onclick={() => (showConfirm = false)}>
              Cancel
            </button>
            <button class="cf-confirm-ok" onclick={handleConfirm}>Confirm</button>
          </div>
        </div>
      </div>
    {:else}
      <button
        class="cf-submit-btn"
        class:cf-submit-btn--submitting={submitState === "submitting"}
        onclick={handleSubmit}
        disabled={submitState === "submitting"}
      >
        {submitState === "submitting" ? "Submitting…" : submitState === "error" ? "Try again" : "Submit"}
      </button>
    {/if}
  {/if}
</div>
