// src/components/RouteSelector.jsx
import { useNavigate } from 'react-router-dom'
import './RouteSelector.css'

export default function RouteSelector({ project, city, routeId, route }) {
  const navigate = useNavigate()
  const handleNav = () => navigate(`/${project}/${city}/${routeId}`)
  return (
    <div
      role="button"
      tabIndex={0}
      onClick={handleNav}
      onKeyDown={e => (e.key === 'Enter' || e.key === ' ') && handleNav()}
      className="route-card"
    >
      <div className="route-card__name">
        {routeId.replace(/_/g, ' ')}
      </div>
      <div className="route-card__description">{route.description}</div>
      <div className="route-card__stops">
        {route.locations.length} stop{route.locations.length !== 1 ? 's' : ''}
      </div>
    </div>
  )
}

// src/components/RouteSelector.svelte
<script lang="ts">
  import { push } from "svelte-spa-router";
  import type { RouteDefinition } from "../types/data";
  import "./RouteSelector.css";

  let {
    project,
    city,
    routeId,
    route,
  }: {
    project: string;
    city: string;
    routeId: string;
    route: RouteDefinition;
  } = $props();

  function handleNav() {
    push(`/${project}/${city}/${routeId}`);
  }
</script>

<div
  role="button"
  tabindex="0"
  class="route-card"
  onclick={handleNav}
  onkeydown={(evt) => (evt.key === "Enter" || evt.key === " ") && handleNav()}
>
  <div class="route-card__name">{routeId.replace(/_/g, " ")}</div>
  <div class="route-card__description">{route.description}</div>
  <div class="route-card__stops">
    {route.locations.length} stop{route.locations.length !== 1 ? "s" : ""}
  </div>
</div>
