// src/components/TitleBar.jsx
import { useState, useContext } from "react";
import { useNavigate } from "react-router-dom";
import { useTheme } from "../theme/ThemeContext";
import { TitleBarContext } from "../theme/TitleBarContext";
import { themes } from "../theme/themes";
import { useFontSize } from "../theme/FontSizeContext";
import { useAuth } from "../auth/AuthContext";
import "./TitleBar.css";

export default function TitleBar() {
  const { theme, themeName, setThemeName } = useTheme();
  const { fontSize, setFontSize, SIZES } = useFontSize();
  const { titleBar } = useContext(TitleBarContext);
  const { title, progress, backPath } = titleBar;
  const { activeAuth, logout } = useAuth();
  const navigate = useNavigate();
  const [menuView, setMenuView] = useState(null);

  function closeMenu() {
    setMenuView(null);
  }

  return (
    <div className="titlebar">
      <div className="titlebar__row">
        <div className="titlebar__left">
          {backPath ? <button
              onClick={() => navigate(backPath)}
              aria-label="Back"
              className="titlebar__back-btn"
            >
              ←
            </button> : null}
          <span className="titlebar__title">{title}</span>
        </div>

        <div className="titlebar__menu-wrap">
          <button
            onClick={() => setMenuView((v) => (v ? null : "root"))}
            aria-label="Menu"
            className="titlebar__menu-btn"
          >
            ☰
          </button>

          {menuView ? <div className="titlebar__dropdown">
              {menuView === "root" ? <>
                  <button
                    onClick={() => setMenuView("profile")}
                    className="titlebar__menu-item"
                  >
                    <span className="titlebar__menu-item-label">Profile</span>
                    <span className="titlebar__menu-item-arrow">›</span>
                  </button>
                  <button
                    onClick={() => setMenuView("themes")}
                    className="titlebar__menu-item"
                  >
                    <span className="titlebar__menu-item-label">Themes</span>
                    <span className="titlebar__menu-item-arrow">›</span>
                  </button>
                  <button
                    onClick={() => setMenuView("fontsize")}
                    className="titlebar__menu-item"
                  >
                    <span className="titlebar__menu-item-label">Text Size</span>
                    <span className="titlebar__menu-item-arrow">›</span>
                  </button>
                </> : null}

              {menuView === "profile" ? <>
                  <button
                    onClick={() => setMenuView("root")}
                    aria-label="Back to menu"
                    className="titlebar__submenu-header"
                  >
                    <span className="titlebar__submenu-back">‹</span>
                    <span className="titlebar__submenu-title">Profile</span>
                  </button>
                  <div className="titlebar__profile-body">
                    <div className="titlebar__profile-field">
                      <div className="titlebar__profile-label">Team</div>
                      <div className="titlebar__profile-value">
                        {activeAuth?.teamName || "—"}
                      </div>
                    </div>
                    <div
                      className="titlebar__profile-field"
                      style={{ marginBottom: 16 }}
                    >
                      <div className="titlebar__profile-label">Contact</div>
                      <div className="titlebar__profile-value--contact">
                        {activeAuth?.contact || "—"}
                      </div>
                    </div>
                    <button
                      onClick={async () => {
                        await logout();
                        closeMenu();
                      }}
                      className="titlebar__signout-btn"
                    >
                      Sign out
                    </button>
                  </div>
                </> : null}

              {menuView === "themes" ? <>
                  <button
                    onClick={() => setMenuView("root")}
                    aria-label="Back to menu"
                    className="titlebar__submenu-header"
                  >
                    <span className="titlebar__submenu-back">‹</span>
                    <span className="titlebar__submenu-title">Themes</span>
                  </button>
                  {Object.keys(themes).map((name) => (
                    <button
                      key={name}
                      onClick={() => {
                        setThemeName(name);
                        closeMenu();
                      }}
                      className="titlebar__theme-btn"
                      style={{
                        background:
                          name === themeName ? theme.accent : "transparent",
                        color: name === themeName ? theme.barText : theme.text,
                        fontWeight: name === themeName ? 700 : 400,
                      }}
                    >
                      <span>{name}</span>
                      {name === themeName ? <span className="titlebar__theme-check">✓</span> : null}
                    </button>
                  ))}
                </> : null}
              {menuView === "fontsize" ? <>
                  <button
                    onClick={() => setMenuView("root")}
                    aria-label="Back to menu"
                    className="titlebar__submenu-header"
                  >
                    <span className="titlebar__submenu-back">‹</span>
                    <span className="titlebar__submenu-title">Text Size</span>
                  </button>
                  {SIZES.map((size) => (
                    <button
                      key={size}
                      onClick={() => {
                        setFontSize(size);
                        closeMenu();
                      }}
                      className="titlebar__theme-btn"
                      style={{
                        background:
                          size === fontSize ? theme.accent : "transparent",
                        color: size === fontSize ? theme.barText : theme.text,
                        fontWeight: size === fontSize ? 700 : 400,
                      }}
                    >
                      <span style={{ textTransform: "capitalize" }}>
                        {size}
                      </span>
                      {size === fontSize ? <span className="titlebar__theme-check">✓</span> : null}
                    </button>
                  ))}
                </> : null}
            </div> : null}
        </div>
      </div>

      {progress ? <div
          data-testid="progress-bar"
          className="titlebar__progress-track"
          style={{ height: 6 }}
        >
          <div
            className="titlebar__progress-fill"
            style={{ width: `${(progress.current / progress.total) * 100}%` }}
          />
        </div> : null}
    </div>
  );
}

// src/components/TitleBar.svelte
<script lang="ts">
  import { push } from "svelte-spa-router";
  import { titleBarStore } from "../stores/titleBarStore";
  import { themeStore } from "../stores/themeStore";
  import { fontSizeStore, FONT_SIZES } from "../stores/fontSizeStore";
  import { authStore } from "../stores/authStore";
  import { themes } from "../theme/themes";
  import type { ThemeName } from "../types/theme";
  import type { FontSize } from "../stores/fontSizeStore";
  import "./TitleBar.css";

  let menuView = $state<string | null>(null);

  function closeMenu() {
    menuView = null;
  }

  function handleBack() {
    if ($titleBarStore.backPath) {
      push($titleBarStore.backPath);
    }
  }
</script>

<div class="titlebar">
  <div class="titlebar__row">
    <div class="titlebar__left">
      {#if $titleBarStore.backPath}
        <button
          onclick={handleBack}
          aria-label="Back"
          class="titlebar__back-btn"
        >
          ←
        </button>
      {/if}
      <span class="titlebar__title">{$titleBarStore.title}</span>
    </div>

    <div class="titlebar__menu-wrap">
      <button
        onclick={() => menuView = menuView ? null : "root"}
        aria-label="Menu"
        class="titlebar__menu-btn"
      >
        ☰
      </button>

      {#if menuView}
        <div class="titlebar__dropdown">
          {#if menuView === "root"}
            <button
              onclick={() => menuView = "profile"}
              class="titlebar__menu-item"
            >
              <span class="titlebar__menu-item-label">Profile</span>
              <span class="titlebar__menu-item-arrow">›</span>
            </button>
            <button
              onclick={() => menuView = "themes"}
              class="titlebar__menu-item"
            >
              <span class="titlebar__menu-item-label">Themes</span>
              <span class="titlebar__menu-item-arrow">›</span>
            </button>
            <button
              onclick={() => menuView = "fontsize"}
              class="titlebar__menu-item"
            >
              <span class="titlebar__menu-item-label">Text Size</span>
              <span class="titlebar__menu-item-arrow">›</span>
            </button>
          {/if}

          {#if menuView === "profile"}
            <button
              onclick={() => menuView = "root"}
              aria-label="Back to menu"
              class="titlebar__submenu-header"
            >
              <span class="titlebar__submenu-back">‹</span>
              <span class="titlebar__submenu-title">Profile</span>
            </button>
            <div class="titlebar__profile-body">
              <div class="titlebar__profile-field">
                <div class="titlebar__profile-label">Team</div>
                <div class="titlebar__profile-value">
                  {$authStore.activeAuth?.teamName ?? "—"}
                </div>
              </div>
              <div class="titlebar__profile-field" style="margin-bottom: 16px">
                <div class="titlebar__profile-label">Contact</div>
                <div class="titlebar__profile-value--contact">
                  {$authStore.activeAuth?.contact ?? "—"}
                </div>
              </div>
              <button
                onclick={async () => {
                  await authStore.logout();
                  closeMenu();
                }}
                class="titlebar__signout-btn"
              >
                Sign out
              </button>
            </div>
          {/if}

          {#if menuView === "themes"}
            <button
              onclick={() => menuView = "root"}
              aria-label="Back to menu"
              class="titlebar__submenu-header"
            >
              <span class="titlebar__submenu-back">‹</span>
              <span class="titlebar__submenu-title">Themes</span>
            </button>
            {#each Object.keys(themes) as themeName (themeName)}
              <button
                onclick={() => {
                  themeStore.setThemeName(themeName as ThemeName);
                  closeMenu();
                }}
                class="titlebar__theme-btn"
                style="background: {themeName === $themeStore.themeName ? $themeStore.theme.accent : "transparent"}; color: {themeName === $themeStore.themeName ? $themeStore.theme.barText : $themeStore.theme.text}; font-weight: {themeName === $themeStore.themeName ? 700 : 400}"
              >
                <span>{themeName}</span>
                {#if themeName === $themeStore.themeName}
                  <span class="titlebar__theme-check">✓</span>
                {/if}
              </button>
            {/each}
          {/if}

          {#if menuView === "fontsize"}
            <button
              onclick={() => menuView = "root"}
              aria-label="Back to menu"
              class="titlebar__submenu-header"
            >
              <span class="titlebar__submenu-back">‹</span>
              <span class="titlebar__submenu-title">Text Size</span>
            </button>
            {#each FONT_SIZES as fontSizeEntry (fontSizeEntry)}
              <button
                onclick={() => {
                  fontSizeStore.setFontSize(fontSizeEntry);
                  closeMenu();
                }}
                class="titlebar__theme-btn"
                style="background: {fontSizeEntry === $fontSizeStore.fontSize ? $themeStore.theme.accent : "transparent"}; color: {fontSizeEntry === $fontSizeStore.fontSize ? $themeStore.theme.barText : $themeStore.theme.text}; font-weight: {fontSizeEntry === $fontSizeStore.fontSize ? 700 : 400}"
              >
                <span style="text-transform: capitalize">{fontSizeEntry}</span>
                {#if fontSizeEntry === $fontSizeStore.fontSize}
                  <span class="titlebar__theme-check">✓</span>
                {/if}
              </button>
            {/each}
          {/if}
        </div>
      {/if}
    </div>
  </div>

  {#if $titleBarStore.progress}
    <div
      data-testid="progress-bar"
      class="titlebar__progress-track"
      style="height: 6px"
    >
      <div
        class="titlebar__progress-fill"
        style="width: {($titleBarStore.progress.current / $titleBarStore.progress.total) * 100}%"
      ></div>
    </div>
  {/if}
</div>
